-- ==========================================================
-- Church Parking Violation Tracker v1.0 - Supabase setup
-- Run this ONCE in Supabase Dashboard -> SQL Editor.
-- ==========================================================

begin;

create table if not exists public.violations (
    id bigint generated by default as identity primary key,
    legacy_local_id bigint unique,
    plate_number text not null,
    state text not null default 'TX',
    violation_type text not null,
    location text not null,
    notes text,
    warning_level integer not null,
    warning_label text not null,
    recorded_at timestamptz not null,
    warned_by text,
    entered_by text,
    photo_path text,
    photo_source text,
    status text not null default 'Active'
        check (status in ('Active', 'Dismissed')),
    created_at timestamptz not null default now(),
    dismissed_at timestamptz,
    dismissed_by text
);

create index if not exists violations_plate_idx
    on public.violations (plate_number);

create index if not exists violations_status_idx
    on public.violations (status);

create index if not exists violations_recorded_at_idx
    on public.violations (recorded_at desc);

alter table public.violations enable row level security;

-- v1.0 talks to Supabase only from the trusted Streamlit server.
-- Browser/client roles receive no direct table access.
revoke all on table public.violations from anon, authenticated;
grant select, insert, update, delete on table public.violations to service_role;
grant usage, select on all sequences in schema public to service_role;


-- ----------------------------------------------------------
-- Atomic create function.
-- The advisory lock prevents two volunteers from assigning
-- the same warning number to the same plate simultaneously.
-- ----------------------------------------------------------
create or replace function public.create_parking_violation(
    p_plate_number text,
    p_state text,
    p_violation_type text,
    p_location text,
    p_notes text,
    p_recorded_at timestamptz,
    p_warned_by text,
    p_entered_by text,
    p_photo_path text default null,
    p_photo_source text default null
)
returns table (
    id bigint,
    warning_level integer,
    warning_label text
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_plate text;
    v_level integer;
    v_label text;
begin
    v_plate := upper(
        regexp_replace(
            coalesce(p_plate_number, ''),
            '[^A-Za-z0-9]',
            '',
            'g'
        )
    );

    if v_plate = '' then
        raise exception 'License plate is required';
    end if;

    perform pg_advisory_xact_lock(hashtextextended(v_plate, 0));

    select count(*)::integer + 1
      into v_level
      from public.violations
     where plate_number = v_plate
       and status = 'Active';

    v_label := case
        when v_level = 1 then 'First Warning'
        when v_level = 2 then 'Second Warning'
        when v_level = 3 then 'Third / Final Warning'
        else 'Repeat Violation / Administrative Review'
    end;

    return query
    insert into public.violations as v (
        plate_number,
        state,
        violation_type,
        location,
        notes,
        warning_level,
        warning_label,
        recorded_at,
        warned_by,
        entered_by,
        photo_path,
        photo_source,
        status
    )
    values (
        v_plate,
        coalesce(nullif(p_state, ''), 'TX'),
        p_violation_type,
        p_location,
        nullif(p_notes, ''),
        v_level,
        v_label,
        p_recorded_at,
        p_warned_by,
        p_entered_by,
        p_photo_path,
        p_photo_source,
        'Active'
    )
    returning
        v.id,
        v.warning_level,
        v.warning_label;
end;
$$;

revoke all on function public.create_parking_violation(
    text, text, text, text, text, timestamptz,
    text, text, text, text
) from public, anon, authenticated;

grant execute on function public.create_parking_violation(
    text, text, text, text, text, timestamptz,
    text, text, text, text
) to service_role;


-- ----------------------------------------------------------
-- Dashboard metrics.
-- ----------------------------------------------------------
create or replace function public.parking_dashboard_metrics(
    p_timezone text default 'America/Chicago'
)
returns table (
    total_active bigint,
    today_count bigint,
    unique_vehicles bigint,
    repeat_vehicles bigint
)
language sql
security definer
set search_path = public
as $$
    select
        (select count(*)
           from public.violations
          where status = 'Active') as total_active,

        (select count(*)
           from public.violations
          where status = 'Active'
            and (recorded_at at time zone p_timezone)::date =
                (now() at time zone p_timezone)::date) as today_count,

        (select count(distinct plate_number)
           from public.violations
          where status = 'Active') as unique_vehicles,

        (select count(*)
           from (
               select plate_number
                 from public.violations
                where status = 'Active'
                group by plate_number
               having count(*) >= 3
           ) repeaters) as repeat_vehicles;
$$;

revoke all on function public.parking_dashboard_metrics(text)
    from public, anon, authenticated;
grant execute on function public.parking_dashboard_metrics(text)
    to service_role;


-- ----------------------------------------------------------
-- Top active vehicles.
-- ----------------------------------------------------------
create or replace function public.parking_top_vehicles(
    p_limit integer default 25
)
returns table (
    plate_number text,
    active_violations bigint,
    last_seen timestamptz
)
language sql
security definer
set search_path = public
as $$
    select
        v.plate_number,
        count(*) as active_violations,
        max(v.recorded_at) as last_seen
    from public.violations v
    where v.status = 'Active'
    group by v.plate_number
    order by count(*) desc, max(v.recorded_at) desc
    limit greatest(1, least(coalesce(p_limit, 25), 100));
$$;

revoke all on function public.parking_top_vehicles(integer)
    from public, anon, authenticated;
grant execute on function public.parking_top_vehicles(integer)
    to service_role;


-- ----------------------------------------------------------
-- Private Storage bucket for violation photos.
-- 10 MB maximum, normalized JPEG only.
-- No public policies are created. Access is through the
-- server-side secret key only.
-- ----------------------------------------------------------
insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'violation-photos',
    'violation-photos',
    false,
    10485760,
    array['image/jpeg']
)
on conflict (id) do update
set
    public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

commit;
